### ISSUE TITLE
Add GHC Happy Hour Hosted by Publicis.Sapient 

### ISSUE THREAD

**Issue by swetakum** [missCarrieMah/GHC-Events#17]
GHC Happy Hour Hosted by Publicis.Sapient - 
September 26
https://www.eventbrite.com/e/ghc-happy-hour-hosted-by-publicissapient-tickets-49894269102?aff=ebdssbdestsearch

**Comment by craftypixeldesigns** [comment]
Added to commit [ee20ef](https://github.com/missCarrieMah/GHC-Events/commit/ee20ef6b0d96c27d2174ab0510bdf614d0a29c27)
