### ISSUE TITLE
Google GHC event in WA

### ISSUE THREAD

**Issue by charlottetan** [missCarrieMah/GHC-Events#22]
not in Houston:
https://ghcconnectkirkland.splashthat.com/

**Comment by charlottetan** [comment]
(for friends who can't attend GHC)

**Comment by craftypixeldesigns** [comment]
Thanks! Added to commit [5ff25a1](https://github.com/missCarrieMah/GHC-Events/commit/5ff25a1db3533b289ad2846569c92e70a12b8c59)
