### ISSUE TITLE
Adding MSFT AI & Mixed Reality event link

### ISSUE THREAD

**Issue by misbahuz** [missCarrieMah/GHC-Events#35]
Hi! Just submitting request to add in a link to apply/RSVP for women interested in working in AI and Mixed Reality at Microsoft. Team is taking applications for our private dinners on Thursday 9/27 here: https://bit.ly/2znLkUb

**Comment by craftypixeldesigns** [comment]
Thanks so much for the share! You can see your change on commit [3954e7a](https://github.com/missCarrieMah/GHC-Events/commit/3954e7a3a1189e7ea3e71919d2ad573f087dae8a)
