### ISSUE TITLE
Twitter Event - #GHCBeachBoardwalk

### ISSUE THREAD

**Issue by kyraseevers** [missCarrieMah/GHC-Events#39]
The link to RSVP and find more info is here: https://ghc2019.splashthat.com/?utm_campaign=RE_NL_GBL_ALL_What%27s%20Happening%20%40TwitterU%20%7C%20Excited%20for%20Fall%21%20_080819&utm_medium=email&utm_source=Eloqua&elqTrackId=9D4CC187C105933B27B1C286AAA5F69E&elq=8fe05528b2ec48d6a53664082fa68de1&elqaid=12827&elqat=1&elqCampaignId=6292

"Join us at #GHCBeachBoardwalk to chat with our employees (we call them Tweeps) who are working on challenging problems every day. You’ll also have the chance to engage with some of our @TwitterWomen over food, games, and music.

Wednesday, October 2nd
7:00pm - 9:00pm ET
Rosen Center Hotel - Executive Ballroom | 9840 International Dr"

**Comment by jenniferrospad-wf** [comment]
Closing - event has been added.
