### ISSUE TITLE
AWS event

### ISSUE THREAD

**Issue by Keerthu-Baskar** [missCarrieMah/GHC-Events#44]
https://aws-bts-orlando.splashthat.com/

**Comment by jenniferrospad-wf** [comment]
Feel free to open a pull request!

**Comment by craftypixeldesigns** [comment]
Added event in [this commit](https://github.com/missCarrieMah/GHC-Events/commit/86c57ac911b81997a0422b97a032fad8b4ebb02e#diff-04c6e90faac2675aa89e2176d2eec7d8)
