### ISSUE TITLE
Dell Technologies Webinar Sep 12th

### ISSUE THREAD

**Issue by carvalhomariana** [missCarrieMah/GHC-Events#45]
**WEBINAR**: _Getting the most out of the Grace Hopper Celebration_
RSVP here: https://lnkd.in/edF-wq6
Join the webinar at 12pm EST / 9am PST: https://dell.zoom.us/wc/join/108583751

**Comment by craftypixeldesigns** [comment]
Added event for awareness in [this commit](https://github.com/missCarrieMah/GHC-Events/commit/86c57ac911b81997a0422b97a032fad8b4ebb02e#diff-04c6e90faac2675aa89e2176d2eec7d8)
