### ISSUE TITLE
Network Like a Girl Networking Event by Dell Technologies

### ISSUE THREAD

**Issue by carvalhomariana** [missCarrieMah/GHC-Events#46]
When: OCTOBER 2, 5:30pm - 7:30pm
Where: ROSEN CENTRE HOTEL, HARRY'S PATIO

RSVP here: https://docs.google.com/forms/d/e/1FAIpQLSeHEU0EBxXYgvCB4yYagwsbhHSoxQQsD4CLwFWf3J9gRSP2yA/closedform

**Comment by jenniferrospad-wf** [comment]
Looks like registration is closed for this one already - is it possible that this is a link from a previous year?

**Comment by carvalhomariana** [comment]
> Looks like registration is closed for this one already - is it possible that this is a link from a previous year?

it is for this year 2019! But I think they just closed it

**Comment by craftypixeldesigns** [comment]
Added event for awareness in [this commit](https://github.com/missCarrieMah/GHC-Events/commit/86c57ac911b81997a0422b97a032fad8b4ebb02e#diff-04c6e90faac2675aa89e2176d2eec7d8)
