### ISSUE TITLE
Add IBM Grace Hopper Celebration Party

### ISSUE THREAD

**Issue by anamita** [missCarrieMah/GHC-Events#48]
For Wednesday 10/2:

Event: IBM Grace Hopper Celebration
Company: IBM
Location: The Wizarding World of Harry Potter -- 6000 Universal Blvd, Orlando, FL 32819
Time: 9:00 PM - 12:00 AM
Notes: Program your first quantum computer at the IBM booth for a chance to attend!

**Comment by jenniferrospad-wf** [comment]
Wednesday is October 2nd - did you mean Wednesday 10/2, or Friday 10/4?

**Comment by anamita** [comment]
Wednesday October 2nd. Apologies.

**Comment by Keerthu-Baskar** [comment]
where is the link???

**Comment by jenniferrospad-wf** [comment]
Added!
